# semgrep:
#   name: Semgrep 

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   semgrep:
#     runs-on: ubuntu-latest
#     name: Run Semgrep
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'

#       - name: Install Semgrep
#         run: pip install semgrep

#       - name: Run Semgrep
#         run: semgrep --config auto --sarif -o semgrep-results.sarif

#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: semgrep-results.sarif
