name: Semgrep

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorpsvc/semgrep:latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3

      - name: "Execute semgrep"
        run: semgrep ci
        env:
          SEMGREP_RULES: p/default
