name: Semgrep

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3

      - name: "Execute semgrep"
        run: semgrep ci --sarif --sarif-output=semgrep.sarif 

        env:
          SEMGREP_RULES: p/default

      - name: "Upload SARIF file for GitHub CodeQL"
        uses: github/codeql-actions/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
